version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.23

  pre_build:
    commands:
      - echo Logging in to check Go version...
      - go version
      - echo Downloading dependencies...
      - go mod download

  build:
    commands:
      - echo Build started on `date`
      - echo Building Go application...
      - CGO_ENABLED=0 GOOS=linux go build -o user main.go
      - echo Build completed successfully

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Listing build artifacts...
      - ls -la user

artifacts:
  files:
    - user
  name: user-build-$(date +%Y-%m-%d-%H-%M-%S)